### PR TITLE
feat: Add typescript declaration file

### PR DESCRIPTION
**Pull request by dmaccormack**

### CODE REVIEW

**Comment by dmaccormack** [comment]
Closes #97

**Comment by dmaccormack** [comment]
Closes #165

**Comment by darcyparker** [comment]
Looks good. Thanks for adding typescript definitions.

The only thing I noticed... (a nitpick) is that while `type JsonURLStringifyOptions = {...}` is valid, usually it is written as `interface JsonURLStringifyOptions { ... }`.  `JsonURLParseOptions` shares many properties... so you could have defined a base interface and used `extends`.

Regardless... this is useable and I appreciate having typescript definitions now.

**Comment by dmaccormack** [comment]
> The only thing I noticed... (a nitpick) is that while `type JsonURLStringifyOptions = {...}` is valid, usually it is written as `interface JsonURLStringifyOptions { ... }`. `JsonURLParseOptions` shares many properties... so you could have defined a base interface and used `extends`.

OK, good to know. I used this a reference:
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

Is the preference for `interface` an idiom?

While JsonURLParseOptions and JsonURLStringifyOptions do indeed share many property names, the value types sometimes differ, and the documentation is written from the POV of parse() and stringify(), respectively. That's why I chose to model them as distinct types.

**Comment by darcyparker** [comment]
The referenced you used is good.  And it gives good examples comparing how a `type` vs `interface` can be extended.  If an interface is chosen, it sometimes makes reading error messages clearer.  But I don't think it really matters here because these types have a simple structure.  I suppose `interface` is just a pattern I am used to seeing more and it struck me as different even though I don't have a good reason to say one is better than the other here.

If you think they are sufficiently distinct and that if you ever have to change some property it will only effect parse() or only stringify() and not both, then I think using `type` is a good.  Maybe just keep it in the back in your mind so that if in the future you find your editing the same property in 2 places, maybe its worth extracting a common interface between the two.

**Pull request merged**
